name: Deploy to S3

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install
        working-directory: .  # Run npm install in the root directory

      - name: Build
        run: npm run build
        working-directory: .  # Build in the root directory

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@0.5.0
        with:
          args: --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: './build'  # Adjusted to point to the build folder created in the root
          DEST_DIR: 's3://${{ secrets.S3_BUCKET }}'
